### PR TITLE
Evan Glaser Challenge 1.0

### PR DESCRIPTION
**Pull request by eglaser25**
-Implemented functionality to make API call to the public endpoint listed, then convert the response object into flat array
-Built test with mock data to ensure handler works properly without internet connection

### CODE REVIEW

**Comment by funador** [comment]
Hi Evan,

Going to close this one out.  Can you please create a PR in a private repo via the instructions in the [Readme](https://github.com/helloextend/lambda-backend-challenge/blob/master/README.md).  

Thank you

**Comment by eglaser25** [comment]
HI Jesse,

My mistake! Sorry about that.

I've made a PR from my Challenge branch to Master. Let me know if you'd
like me to add you as a reviewer or anything like that.

Thanks,
Evan

**Comment by funador** [comment]
Yup that would be great, if you could add me as a collaborator @funador.  Cheers

**Comment by eglaser25** [comment]
Hey Jesse,

Sorry for the mixup from my end. I believe we should be good to go now with
you as a collaborator in my private repo called 'extend-challenge'. I just
submitted a PR <https://github.com/eglaser25/extend-challenge/pull/1> from
my branch 'main' to 'extend-original'
<https://github.com/eglaser25/extend-challenge/pull/1>.

Thanks again for helping me get it squared away, and if there's anything
else I can do let me know.

Evan

**Pull request closed without merging**
